version : '3'

networks:
  prom:

services:

  prometheus:
    image   : prom/prometheus
    hostname: prometheus
    ports   :
    - "9090:9090"
    volumes :
    - /workspaces/openaf/ppp/prometheus.yml:/etc/prometheus/prometheus.yml
    - prometheus:/prometheus
    networks:
    - prom

  pushgateway:
    image   : prom/pushgateway
    hostname: pushgateway
    ports   :
    - "9091:9091"
    networks:
    - prom
  

  # Login with admin/admin
  grafana:
    image   : grafana/grafana
    hostname: grafana
    ports   :
    - "3000:3000"
    volumes :
    - grafana:/var/lib/grafana
    networks:
    - prom

volumes:
  prometheus:
  grafana:
