ojob:
  #sequential: true
  #async: true
  #catch: |
  #  print("---");
  #  sprint(exception);
  #  return false;

jobs: 
  - name: t1
    exec: |
      print(1);
      global.c = 0;
      global.rty = {};

  - name: t2
    typeArgs:
      single: true
    exec: |
      print("vou fazer = " + args.a + " com retry " + args.retry);
      global.rty[args.a] = (isUnDef(global.rty[args.a]) ? 1 : global.rty[args.a]++);
      global.c++;
      throw global.c;
    catch: |
      print(args.a);
      
      if (!args.retry) ow.oJob.add2Todo({ name: "t2", args: merge(args, { retry: true }) });
      return true;

todo: 
  - t1
  - name: t2
    #args:
    #  a: t1
    args:
      - a: a1
        retry: false
      - a: a2
        retry: false
      - a: a3
        retry: false