jobs:
   # Build OpenAF
   - name  : Build OpenAFOS
     exec  : >
        global.path = (isDef(args.path)) ? args.path : ".";
        __expr = "withDir=" + global.path;
        af.load(global.path + "/buildos.js");

   # Repack the recently build openaf
   - name  : Repack OpenAFOS
     deps  :
        - Build OpenAFOS
     exec  : >
        log("Repacking...");
        sh("java -jar " + global.path + "/openaf.jar --repack", "", undefined, true);

   # Copy OpenAF to the right place for use
   - name  : Copy OpenAF
     deps  :
        - Build OpenAFOS
        - Repack OpenAFOS
     exec  : >
        log("Copying...");
        sh("cp " + global.path + "/openaf.jar " + global.path + "/dist/openaf.jar", "", undefined, true);

todo:
   - Build OpenAFOS
   - Repack OpenAFOS
   - Copy OpenAF
