name: Build T8

on:
  push:
    branches: [ t8 ]
  pull_request:
    branches: [ t8 ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # --------------------------
    - name: Cache OpenAF runtime
      uses: actions/cache@v3
      with:
        key : oaf
        path: /tmp/oaf

    # --------------
    - name: Checkouta,e
      uses: actions/checkout@v2

    # -----------------------
    - name: Compile ojob yaml
      uses: openaf/ojob-action@v3
      with:
        ojob: ojob.io/ojob/compile
        args: "source=ojob.yaml target=ojob.json"

    # -------------
    - name: Checkin
      uses: openaf/ojob-action@v3
      with:
        ojob: ojob.io/git/hub/checkIn
        args: 'message="Update\ ojob.json"'

    # --------------------
    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
        java-package: jdk
        architecture: x64

    # -----------
    - name: Build
      uses: openaf/ojob-action@v3
      with:
        ojob: build.yaml
          
    # ----------------------------
    - name: Update openaf.jar.orig
      uses: actions/upload-artifact@v2
      with:
        name: openaf.jar.orig
        path: openaf.jar.orig

    # -----------------------
    - name: Upload openaf.jar
      uses: actions/upload-artifact@v2
      with:
        name: openaf.jar
        path: openaf.jar
